# -*- mode: makefile; -*-

perl5libdir                   = @perl5libdir@
amazondir                     = @perl5libdir@/Amazon
amazon_apidir                 = $(amazondir)/API
amazon_api_poddir             = $(amazondir)/API/Pod
amazon_api_pod_simpledir      = $(amazon_api_poddir)/Simple
amazon_api_botocoredir        = $(amazon_apidir)/Botocore
amazon_api_botocore_shapedir  = $(amazon_apidir)/Botocore/Shape
