#!/bin/bash
# -*- mode: sh; -*-
# Script to create a CPAN distribution containing an AWS API class.

BOTOCORE_PATH=/root/git/botocore

SERVICE="$1"

if test -n "$2"; then
 MODULE_NAME="-m $2"
fi              

cd /scratch

create-service -s $SERVICE $MODULE_NAME -b $BOTOCORE_PATH -f

exit 0;
