#!/bin/bash
# -*- mode: sh; -*-
# Companion script to 'build-dist' which is run the
# 'amazon-api' container for creating CPAN distributions of Amazon AWS
# API modules.

########################################################################
function usage {
########################################################################
    test -n "$1" && echo "error: $1";
    
    cat <<EOT
usage: $0 options

Utility to create a CPAN distribution for an AWS API

Creates a CPAN distribution (tarball) containing the specified AWS API
class. The Perl class create will be named Amazon::AWS::{ModuleName}
where {ModuleName} is the argument you pass to using the -m option. If
you do not pass a module name, the suffix for the calls will be
generated based on these rules:

 - if the service is a TLA (ec2, efs, sqs, etc), the suffix will be
   the uppper case representation of the TLA.

 - if the service name is greater than 3 characters, the suffix will
   be the service name with the first letter upper cased (Example:
   Route53).

Options
-------
-h               help
-m module name   suffix name for the module
-s service name  name of the AWS API service (lower case)

This utility is part of the Amazon::API distribtion.

Examples:

 $0 -s sqs -m SQS

 $0 -s route53 -m Route53
EOT

    exit;
}

# +-------------------------+
# | MAIN SCRIPT STARTS HERE |
# +-------------------------+

while getopts "h?s:m:" arg "$@"; do

    case "${arg}" in

        m)
            module_name="$OPTARG";
            ;;
        
        s)
            api_service="$OPTARG";
            ;;
        
        o)
            output_path="$OPTARG";
            ;;
        
        h)
	    usage;
	    ;;

    esac
done

if test -z "$api_service"; then
    usage;
    exit 1
fi

tmp=$(mktemp -d)

output_path=${output_path:-.}

docker run --rm  -v $tmp:/scratch amazon-api build-dist $api_service $module_name
tarball=$(find $tmp -name '*.tar.gz' 2>/dev/null)

if test -e $tarball; then
    cp $tarball $output_path
fi

rm -rf $tmp
