#!/usr/bin/env bash
# -*- mode: sh; -*-

# build an RPM from a project

set -x -e

if test -n "$1"; then
    project="$1"
    
    if [[ "$project" =~ ^http ]]; then
        git clone $project

        PROJECT=$(basename $project)
    fi
fi
           
PROJECT=${PROJECT:-project}

if ! test -d $PROJECT; then
    echo "no $PROJECT directory"
    exit 1
fi

cd $PROJECT

if ! test -e bootstrap; then
    echo "no bootstrap script"
    exit 1
fi
    
./bootstrap && ./configure --enable-rpmbuild --disable-deps --enable-rpm-build-mode

make && make dist

tarball=$(find . -name '*.tar.gz')

if test -n "$tarball"; then
    rpmbuild -tb $tarball
else
    echo "no tarball"
    exit 1;
fi

rpmfile=$(find /root -name '*.rpm')
test -n $rpmfile && cp $rpmfile /scratch
