version: 0.1

project:
  description: "AWS API base class"
  author:
    name: Rob Lauer
    mailto: rlauer6@comcast.net
pm_module: Amazon::API
path:
  pm_module: ../src/main/perl/lib
  tests: ../src/main/perl/t
extra-files:
  - ../ChangeLog
