name: Amazon-API
on:
  push:
    branches: [ master ]
jobs:
  test-module:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: ./build-github https://github.com/rlauer6/perl-Amazon-API.git
