name: Amazon-API
on:
  push:
    branches: [ master, dev ]
jobs:
  Amazon-API:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: ./builder https://github.com/rlauer6/Amazon-API.git
